name: flutter_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0  # Add FontAwesome icons
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  generate: true # This enables Flutter to automatically generate code for things like localization

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 900

  assets:
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/logo_text.png
    - assets/images/logo_viasoft.png

flutter_launcher_icons:
  android: true # Generate Android icons
  ios: true     # Generate iOS icons
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#1D2024"

internet_speed_test:
  android_use_androidx: true
  ios_use_permissions: true
